name: Daily Text Notification

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  send_weather_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the Python script
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python -u main_helper_code.py
